---
- name: install starman
  apt: name=starman state=present
  tags:
    - eye
    - starman

- name: put eye config
  template: src=starman.rb dest={{ eye_home }}/starman.rb
  notify: reload eye
  tags:
    - eye
    - starman
    - config
  