- name: eye restart starman
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye restart starman"
  become: yes
  become_user: "{{ eye_user }}"

- name: eye reload starman
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye us reload starman"
  become: yes
  become_user: "{{ eye_user }}"

- name: eye stop starman
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye stop starman"
  become: yes
  become_user: "{{ eye_user }}"

- name: systemctl daemon-reload
  shell: systemctl daemon-reload
